# Generated by Django 5.0 on 2023-12-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=50, verbose_name="Category name"),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=250, verbose_name="Product name"),
                ),
                (
                    "product_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ingredients",
                    models.CharField(max_length=250, verbose_name="Ingredients name"),
                ),
                ("imagen", models.ImageField(null=True, upload_to="product")),
            ],
            options={
                "verbose_name_plural": "Products",
            },
        ),
    ]
