# Generated by Django 5.0 on 2023-12-29 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=models.CharField(max_length=250, verbose_name="Ingredients"),
        ),
    ]
