# Generated by Django 5.0 on 2023-12-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_category_alter_product_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
