# Generated by Django 5.0 on 2023-12-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_name",
                    models.CharField(max_length=50, verbose_name="Offer_name name"),
                ),
                ("fecha_inicial_vigente", models.DateField()),
                ("fecha_final_vigente", models.DateField()),
                ("imagen", models.ImageField(upload_to="offer")),
            ],
            options={
                "verbose_name_plural": "ofertas",
            },
        ),
    ]
