# Generated by Django 5.0 on 2024-01-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="offer_name",
            field=models.CharField(max_length=50, verbose_name="Offer name "),
        ),
    ]
